# Generated by Django 3.1.6 on 2021-02-14 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='return_reasons_sku',
            new_name='core_return_reasons_sku',
        ),
    ]
