# Generated by Django 3.1.7 on 2021-03-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210214_0314'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardPanel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
