# Generated by Django 3.1.7 on 2021-03-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_dashboardpanel_dashboard_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardpanel',
            name='dashboard_description',
            field=models.CharField(blank=True, default=None, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='dashboardpanel',
            name='panel_type',
            field=models.CharField(blank=True, choices=[('barchart', 'Return Reasons Bar Chart')], default=None, max_length=127, null=True),
        ),
    ]
