# Generated by Django 3.1.7 on 2021-03-18 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210312_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardpanel',
            name='panel_type',
            field=models.CharField(blank=True, choices=[('barchart', 'Bar Chart'), ('piechart', 'Pie Chart')], default=None, max_length=127, null=True),
        ),
    ]
