# Generated by Django 3.1.7 on 2021-03-18 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210318_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardpanel',
            name='dashboard_link',
            field=models.CharField(blank=True, default=None, max_length=127, null=True),
        ),
    ]
